config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'guesses/create'

  root :to => "home#welcome"

  resources :games, param: :slug, only: [:show, :create, :new] do
    member do
      post 'reveal_word'
      post 'hide_word'
    end
  end

  resources :guesses, only: [:create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
require 'securerandom'

class Game < ApplicationRecord
  has_many :guesses

  before_create :set_slug

  @@wordnik_apikey = "3024754e412d1ecdfb3310b288107465e759f947a2fd612d6"

  def tempScore
    score = 0

    letterValue = 0
    case difficulty
    when "easy"
      letterValue = 30
    when "medium"
      letterValue = 40
    when "hard"
      letterValue = 50
    end

    if (game_won)
      score += lifeBonus = 300 - 20 * (lives)
    end

    score += (correct_guesses) * letterValue
  end

  def last_guess_correct
    if (self.guesses.last).nil?
      false
    else
      self.guesses.last.is_correct(self.word)
    end
  end

  def to_param
    slug
  end

  def word_count
    self[:word].length
  end

  def self.random_word(difficulty)
    case difficulty
    when "easy"
      minCorpusCount = "5000000"
      maxLength = "6"
    when "medium"
      minCorpusCount = "100000"
      maxLength = "10"
    when "hard"
      minCorpusCount = "500"
      maxLength = "12"     
    end

    api_data = HTTP.get("http://api.wordnik.com:80/v4/words.json/randomWord?hasDictionaryDef=true&minCorpusCount=" + minCorpusCount + "&maxCorpusCount=-1&minDictionaryCount=1&maxDictionaryCount=-1&minLength=3&maxLength=" + maxLength + "&api_key=" + @@wordnik_apikey)
    hash = JSON.parse api_data
    return hash["word"].downcase
  end

  def letter_left(letter)
    letters_array = ('a'..'z').to_a

    self.guesses.each do |guess|
      letters_array.delete(guess.letter)
    end

    return letters_array.include? letter
  end

  def has_guess(letter)
    self.guesses.each do |guess|
      if (letter == guess.letter)
        return true
      end
    end
    return false
  end

  def correct_guesses
    number = 0
    self.guesses.each do |guess|
      if (guess.is_correct(self.word))
        number = number + 1
      end
    end
    return number
  end

  def guesses_left
    lives = self[:lives]
    self.guesses.each do |guess|
      if (lives <= 0 )
        return 0
      end
      if !(guess.is_correct(self.word))
        lives = lives - 1
      end
    end
    return lives
  end

  def game_over
    return guesses_left < 1
  end

  def game_won
    self[:word].chars do |letter|
      if (!has_guess(letter))
        return false
      end
    end
    return true
  end

  def hidden_word
    display_string = ""

    if (!self[:hidden])
      self[:word].chars do |letter|
        display_string = display_string + letter + " "
      end
    else
      self[:word].chars do |letter|
        if (has_guess(letter))
          display_string = display_string + letter + " "
        else
          display_string = display_string + "_ "
        end
      end
    end

    return display_string
  end

  def hidden
    self[:hidden]
  end

  private

  def set_slug
    loop do
      self.slug = SecureRandom.urlsafe_base64(4)
      break unless Game.where(slug: slug).exists?
    end
  end

end

app/models/guess.rb
class Guess < ApplicationRecord
  belongs_to :game

  def is_correct(word)
    word.chars do |letter|
      if (self.letter == letter)
        return true
      end
    end
    return false
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  def userName
      self.email
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # Overriding Devise Sign in Methods
  
  def after_sign_in_path_for(resource)
    new_game_url
  end

  def after_sign_out_path_for(resource)
    new_game_url
  end


end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def create
    game = Game.create(game_params)
    redirect_to(game)
  end

  def reveal_word
    game = Game.find_by slug: params[:slug]
    game.hidden = false
    game.save

    redirect_to(game)
  end

  def hide_word
    game = Game.find_by slug: params[:slug]
    game.hidden = true
    game.save

    redirect_to(game)
  end

  def show
    @game = Game.find_by slug: params[:slug]
  end

  private

  def game_params
    params[:game][:word] = params[:game][:word]&.presence || Game.random_word(params[:game][:difficulty])
    params[:game][:hidden] = true
    params[:game]
    params.require(:game).permit(:word, :hidden, :difficulty, :lives)
  end
  
end

app/controllers/guesses_controller.rb
class GuessesController < ApplicationController

  def create
    game = Game.find(params[:game_id])
    @guess = game.guesses.create(guess_parameters)
    redirect_to(game)

  end

end

private

def guess_parameters
  params.permit(:letter)
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def welcome
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/guesses_helper.rb
module GuessesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/games/new.html.erb
<%= stylesheet_link_tag "new_game" %>

<script>
    fadeOutAlert()
</script>

<nav class="navbar navbar-expand bg-primary navbar-dark">
  <div class="container-fluid">
    <ul class="nav navbar-nav">
      <li><%= link_to "Home", {:controller => "home", :action => "welcome"}, :method => :get, :class => "nav-link active" %></li>
      <li><%= link_to "New Game", {:controller => "games", :action => "new"}, :method => :get, :class => "nav-link active" %></li>
    </ul>
    <ul class="nav navbar-nav">
      <% if user_signed_in? %>
        <li> <%= link_to current_user.email, edit_user_registration_path, :class => "nav-link active" %> </li>
        <li> <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => "nav-link active" %> </li>
      <% else %>
        <li> <%= link_to "Sign Up", new_user_registration_path, :class => "nav-link active" %> </li>
        <li> <%= link_to "Login", new_user_session_path, :class => "nav-link active" %> </li>
      <% end %>
    </ul>
  </div>
</nav>


<div class="container">
  <%= form_for Game.new,
               html: {class: "nifty_form"} do |f| %>

    <div class="row">
      <div class="col-sm">
        <div class="word_field">
          <%= f.text_field :word, :size => "30", :placeholder => "enter word", :class => "input" %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-sm">
        <div class="input_text_container">
          Leave blank to play with a randomly selected word
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-sm">
        <div class="btn-group btn-group-toggle difficulty_container" data-toggle="buttons">
          <label class="btn btn-outline-success difficulty">
            <%= f.radio_button :difficulty, 'easy', :checked => false %> Easy
          </label>
          <label class="btn btn-outline-warning difficulty active">
            <%= f.radio_button :difficulty, 'medium', :checked => true %> Medium
          </label>
          <label class="btn btn-outline-danger difficulty">
            <%= f.radio_button :difficulty, 'hard', :checked => false %> Hard
          </label>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-sm">
        <div class="slider_container">
          <%= f.range_field :lives, :in => 1..15, :step => 1, :class => "slider", :id => "lives_slider" %>
          <script>

              var lives_array = [];

              var lives_slider = document.getElementById("lives_slider")
              var lives_max = document.getElementById("lives_slider").max

              var drawHearts = function () {

                  console.log(lives_array)
                  for (var j = 0; j < lives_array.length; j++) {
                      console.log(lives_array[j])
                      document.getElementById("hearts_container").removeChild(lives_array[j])
                  }

                  lives_array = [];

                  var lives = document.getElementById("lives_slider").value

                  for (var i = 0; i < lives; i++) {
                      var newHeart = document.createElement("img")
                      newHeart.src = '<%= asset_path("heart.png") %>'
                      newHeart.className = "heart_sprite"
                      document.getElementById("hearts_container").appendChild(newHeart)
                      lives_array = lives_array.concat(newHeart)
                  }

                  console.log("Lives: " + lives)
                  console.log("Lives Max: " + lives_max)

                  for (var k = 0; k < (lives_max - lives); k++) {
                      console.log("Loop")
                      var newHeart = document.createElement("img")
                      newHeart.src = '<%= asset_path("heart_grey.png") %>'
                      newHeart.className = "heart_sprite"
                      document.getElementById("hearts_container").appendChild(newHeart)
                      lives_array = lives_array.concat(newHeart)
                  }
              }

              lives_slider.oninput = drawHearts;

              window.onload = drawHearts
          </script>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-sm">
        <div class="lives_container" id="hearts_container">

        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-sm">
        <div class="button_container">
          <%= f.submit "Create Game", :class => "btn btn-primary" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/games/show.html.erb
<%= stylesheet_link_tag "show" %>

<script>
  $(document).ready(function() { 

    var myvar = <%= @game.last_guess_correct %>

    if (myvar){
      var d = document.getElementById("score_value");
      console.log(d);
      d.classList.add("animation");
      console.log(d.classList);
    }
  
  });

</script>


<nav class="navbar navbar-expand bg-primary navbar-dark">
  <div class="container-fluid">
    <ul class="nav navbar-nav">
      <li><%= link_to "Home", {:controller => "home", :action => "welcome"}, :method => :get, :class => "nav-link active" %></li>
      <li><%= link_to "New Game", {:controller => "games", :action => "new"}, :method => :get, :class => "nav-link active" %></li>
    </ul>
  </div>
</nav>

<div class = score>
  SCORE: <div id = "score_value"> <%= @game.tempScore %> </div>
</div>

<div id = ui>
  <div id = word>
  <%= @game.hidden_word %>
  </div>

  <div id = letter_buttons>
    <% ('a'..'z').to_a.each do |letter| %>
      <% if letter == 'j' || letter == 's' %>
        <%= simple_format("\n") %>
      <% end %>
      <% if @game.letter_left(letter) %>
        <%= button_to letter, guesses_create_path(Guess.new),
        :method => :get, params: {game_id: @game.id, letter: letter},
        form: {style: 'display:inline-block;'}, :disabled => @game.game_over || @game.game_won, :class => "btn btn-primary" %>
      <% else %>
        <%= button_to letter, guesses_create_path(Guess.new),
        :method => :get, params: {game_id: @game.id, letter: letter},
        form: {style: 'display:inline-block;'}, :disabled => true, :class => "btn btn-primary", :style => "visibility: hidden;" %>
      <% end %>
  <% end %>
  </div>
</div>

<div id = hangman_image_container>
  <% if @game.game_won %>
    <%= image_tag "victory.png", :digest => false, :id => "hangman_image" %>
  <% else %>
    <%= image_tag "frame" + (15 - @game.guesses_left).to_s + ".png", :digest => false, :id => "hangman_image" %>
  <% end %>
</div>

<div class = "game_buttons g1">
  <div class = btn-group>
    <% if @game.game_won %>
      <%= button_to "Play Again",
       games_path(:game => { :word => "", :hidden => @game.hidden, :difficulty => @game.difficulty, :lives => @game.lives }),
       :class => "btn btn-primary", :id => "new_game_button" %>
      <%= button_to "New Game",
       {:controller => "games", :action => "new"}, :method => :get, :class => "btn btn-primary", :id => "new_game_button" %>
    <% elsif @game.game_over %>
    <%= button_to "Play Again",
     games_path(:game => { :word => "", :hidden => @game.hidden, :difficulty => @game.difficulty, :lives => @game.lives }),
     :class => "btn btn-primary", :id => "new_game_button" %>
      <%= button_to "New Game", {:controller => "games", :action => "new"}, :method => :get, :class => "btn btn-primary", :id => "new_game_button" %>
    <% end %>
  </div>
</div>

<div class = "game_buttons g2">
  <div class = btn-group>
    <% if @game.game_over %>
    <% if @game.hidden %>
      <%= button_to "Show  Word", {:controller => "games", :action => "reveal_word", :game_id => @game.id}, :class => "btn btn-success", :id => "reveal_word_button" %>
    <% else %>
      <%= button_to "Hide Word", {:controller => "games", :action => "hide_word", :game_id => @game.id}, :class => "btn btn-info", :id => "reveal_word_button" %>
    <% end %>
    <% end %>
  </div>
</div>

app/views/guesses/create.html.erb
<h1>Guesses#create</h1>
<p>Find me in app/views/guesses/create.html.erb</p>

app/views/home/welcome.html.erb
<div class="jumbotron text-center">
  <h1>Hangman on Rails</h1>
  <p>A free and open-source online hangman game written in Ruby.</p> 
</div>

<div class = "text-center">
  <div class="btn-group">
    <%= button_to "New Game", {:controller => "games", :action => "new"}, :method => :get, :class => "btn btn-primary" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hangman</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
  </body>
</html>